kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow
  labels:
    type: local
    app: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/airflow"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-postgresql
  labels:
    type: local
    app: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/airflow"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-postgresql
  labels:
    app: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-scheduler
  labels:
    type: local
    app: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/airflow"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-worker
  labels:
    type: local
    app: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/airflow"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-worker
  labels:
    app: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
      storage: 8Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-web
  labels:
    type: local
    app: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/airflow"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-web
  labels:
    app: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
